export const EXPLORER_MIN_QUERY_LENGTH = 2;
export const EXPLORER_MAX_QUERY_LENGTH = 200;
export const EXPLORER_MAX_QUERY_BYTES = 800;
export const EXPLORER_DEFAULT_RESULT_LIMIT = 100;
export const EXPLORER_MAX_RESULT_LIMIT = 500;
