import { MEF_IRPEF_SOURCE } from "@/lib/data/mef-irpef-source";
import { PNRR_CHILDCARE_SOURCE } from "@/lib/data/pnrr-childcare-source";

export type PublicSource = {
  slug: string;
  name: string;
  owner: string;
  area: string;
  cadence: string;
  coverage: string;
  format: string;
  url: string;
  note: string;
  joinKeys?: string[];
};

export const publicSources: PublicSource[] = [
  {
    slug: "bancaditalia",
    name: "Banca d'Italia · debito pubblico",
    owner: "Banca d'Italia",
    area: "Debito lordo della Pubblica amministrazione",
    cadence: "Mensile, con circa 45 giorni di ritardo atteso",
    coverage: "Stock, flussi, strumenti, detentori e vita residua",
    format: "BDS · ZIP · CSV · snapshot JSON verificato",
    url: "https://www.bancaditalia.it/pubblicazioni/finanza-pubblica/index.html",
    note: "Quattro cubi BDS alimentano uno snapshot versionato e riconciliato. Stock e flussi hanno significati e periodi distinti; i dati recenti possono essere rivisti.",
    joinKeys: ["ID serie BDS", "mese"],
  },
  {
    slug: "eurostat",
    name: "Eurostat · conti nazionali",
    owner: "Eurostat",
    area: "Interessi e spesa pubblica totale; entrate fiscali per sottosettore",
    cadence: "Annuale",
    coverage: "Italia: ultimi cinque anni per D41PAY e TE (gov_10a_main); dieci anni di imposte per sottosettore istituzionale (gov_10a_taxag)",
    format: "Statistics API · JSON-stat · snapshot JSON verificato",
    url: "https://ec.europa.eu/eurostat/databrowser/view/gov_10a_main/default/table?lang=en",
    note: "Le quote sono derivazioni aritmetiche, non previsioni né attribuzioni di un effetto a un singolo servizio. La quota di imposte contabilizzata da un sottosettore dipende dal denominatore scelto e non indica dove il denaro resta.",
    joinKeys: ["anno", "na_item", "sector"],
  },
  {
    slug: "siope",
    name: "SIOPE / SIOPE+",
    owner: "RGS · Banca d'Italia",
    area: "Incassi e pagamenti PA",
    cadence: "Controllo orario dei file; aggiornamento quando cambia la fonte",
    coverage: "Adapter attivo: pagamenti di cassa dei Comuni",
    format: "ZIP · CSV · classificazioni contabili",
    url: "https://www.siope.it/documenti/siope2/open/last/",
    note: "Fonte primaria attiva: movimenti mensili nazionali, anagrafiche SIOPE, snapshot comunale versionato e dashboard territoriale.",
  },
  {
    slug: "istat",
    name: "ISTAT SITUAS",
    owner: "Istituto nazionale di statistica",
    area: "Dimensione e caratteristiche dei territori",
    cadence: "Quadri territoriali interrogabili per data",
    coverage: "Comuni italiani 2022–2026: superficie, popolazione e classificazioni territoriali",
    format: "API JSON · snapshot verificato",
    url: "https://situas.istat.it/web/#/territorio",
    note: "Denominatori territoriali per €/km² e contesto geografico; i fattori restano separati e non formano un indice di efficienza.",
    joinKeys: ["codice ISTAT Comune", "codice fiscale Comune", "anno"],
  },
  {
    slug: "openbdap",
    name: "OpenBDAP",
    owner: "Ragioneria Generale dello Stato",
    area: "Bilancio, spesa, SIOPE, opere, PNRR",
    cadence: "Variabile per dataset; pagamenti Stato mensili e consuntivi annuali",
    coverage: "Pagamenti dello Stato, opere pubbliche per CUP e Conto Economico SSN 2024",
    format: "CKAN API · OData · CSV · open data",
    url: "https://bdap-opendata.rgs.mef.gov.it/content/api",
    note: "Connettore attivo: pagamenti dello Stato, dataset MOP, snapshot del Conto Economico consuntivo 2024 degli enti SSN con voci contabili, costi del personale e servizi, e serie storica dello stanziamento enacted per missione della Legge di Bilancio (dal 2017, tassonomia stabile).",
    joinKeys: ["CUP", "codice fiscale titolare", "codice ente RGS"],
  },
  {
    slug: "anac",
    name: "BDNCP / dati aperti ANAC",
    owner: "Autorità Nazionale Anticorruzione",
    area: "Contratti pubblici e ciclo di vita degli appalti",
    cadence: "Mensile per gli open data; endpoint OCDS documentati; Analytics settimanale",
    coverage: "Snapshot CIG 2025 verificato e catalogo ufficiale collegato",
    format: "CSV · JSON · OCDS · API",
    url: "https://dati.anticorruzione.it/opendata/dataset",
    note: "Il MCP espone aggregati verificati della replica CIG 2025 con copertura, hash e limiti. La ricerca live per singolo CIG richiede ancora un indice persistente dedicato.",
    joinKeys: ["CIG", "OCID", "codice fiscale stazione appaltante", "CUP"],
  },
  {
    slug: "inps",
    name: "INPS · invalidità civile",
    owner: "Istituto Nazionale della Previdenza Sociale",
    area: "Prestazioni assistenziali e invalidità civile",
    cadence: "Secondo pubblicazione di rendiconti e analisi statistiche",
    coverage: "Spesa nazionale 2021-2025 e nuove pensioni per 18 regioni 2016-2024",
    format: "PDF istituzionali · snapshot JSON verificato",
    url: "https://www.inps.it/it/it/dati-e-bilanci.html",
    note: "La spesa, lo stock di prestazioni e le nuove decorrenze regionali restano misure separate. Il 2024 territoriale è parziale; i dati pubblici verificati non consentono attribuzioni individuali.",
    joinKeys: ["regione", "anno"],
  },
  {
    slug: "cpt",
    name: "Conti Pubblici Territoriali",
    owner: "Dipartimento per le Politiche di Coesione e per il Sud",
    area: "Entrate e spese pubbliche territorializzate",
    cadence: "Annuale; serie consolidata disponibile 2000-2023",
    coverage: "21 unità territoriali CPT, perimetro Pubblica Amministrazione consolidata",
    format: "CSV · XLSX · snapshot JSON verificato",
    url: "https://politichecoesione.governo.it/it/politica-di-coesione/misurazione-valutazione-e-trasparenza/la-misurazione-delle-politiche-di-coesione/conti-pubblici-territoriali-cpt/i-dati/catalogo-open-cpt/",
    note: "Entrate e spese derivano dalla stessa release e base di cassa. Il saldo è una differenza contabile territorializzata, non una misura di merito né il residuo fiscale di Banca d'Italia.",
    joinKeys: ["codice territorio CPT", "anno"],
  },
  {
    slug: MEF_IRPEF_SOURCE.id,
    name: MEF_IRPEF_SOURCE.public.name,
    owner: MEF_IRPEF_SOURCE.owner,
    area: MEF_IRPEF_SOURCE.public.area,
    cadence: MEF_IRPEF_SOURCE.public.cadence,
    coverage: MEF_IRPEF_SOURCE.public.coverage,
    format: MEF_IRPEF_SOURCE.public.format,
    url: MEF_IRPEF_SOURCE.sourceUrl,
    note: MEF_IRPEF_SOURCE.public.note,
    joinKeys: [...MEF_IRPEF_SOURCE.public.joinKeys],
  },
  {
    slug: "ipa",
    name: "Indice PA (IPA)",
    owner: "AgID",
    area: "Anagrafe degli enti",
    cadence: "Giornaliera",
    coverage: "PA, gestori di servizi pubblici e altri soggetti censiti",
    format: "JSON · XLSX · Data API",
    url: "https://www.indicepa.gov.it/ipa-dati/dataset/enti",
    note: "Connettore attivo: ricerca enti, pagina canonica per Codice IPA, API normalizzata e aggregazioni reali.",
    joinKeys: ["Codice IPA", "codice fiscale", "codice ISTAT"],
  },
  {
    slug: "ipa-struttura",
    name: "IPA · UO e AOO",
    owner: "AgID",
    area: "Articolazioni interne e protocolli",
    cadence: "Giornaliera",
    coverage: "Unità Organizzative e Aree Organizzative Omogenee degli enti IPA",
    format: "CKAN Data API · XLSX · JSON",
    url: "https://www.indicepa.gov.it/ipa-dati/dataset/unita-organizzative",
    note: "Connettore attivo nelle schede ente: UO, relazioni padre-figlio dichiarate da IPA e AOO. Non sostituisce i regolamenti di organizzazione dei singoli enti.",
    joinKeys: ["Codice IPA", "Codice UO", "Codice AOO"],
  },
  {
    slug: "opencoesione",
    name: "OpenCoesione",
    owner: "Dipartimento per le Politiche di Coesione",
    area: "Progetti e pagamenti di coesione",
    cadence: "Bimestrale prevista per i principali dataset",
    coverage: "Aggregato nazionale per stati, temi e nature",
    format: "API · CSV · open data",
    url: "https://opencoesione.gov.it/it/opendata/",
    note: "Dashboard nazionale attiva; nessun drill-down per progetto, soggetto o territorio. Aggiornamento automatico dall'API ufficiale.",
  },
  {
    slug: PNRR_CHILDCARE_SOURCE.id,
    name: PNRR_CHILDCARE_SOURCE.public.name,
    owner: PNRR_CHILDCARE_SOURCE.owner,
    area: PNRR_CHILDCARE_SOURCE.public.area,
    cadence: PNRR_CHILDCARE_SOURCE.public.cadence,
    coverage: PNRR_CHILDCARE_SOURCE.public.coverage,
    format: PNRR_CHILDCARE_SOURCE.public.format,
    url: PNRR_CHILDCARE_SOURCE.sourceUrl,
    note: PNRR_CHILDCARE_SOURCE.public.note,
    joinKeys: [...PNRR_CHILDCARE_SOURCE.public.joinKeys],
  },
  {
    slug: "opencivitas",
    name: "OpenCivitas",
    owner: "Sogei",
    area: "Spesa e fabbisogni standard dei Comuni",
    cadence: "Irregolare; verifica del rilascio 2022 ogni 24 ore",
    coverage: "6.557 Comuni delle Regioni a statuto ordinario, annualità 2022",
    format: "ZIP · CSV · XLSX",
    url: "https://www.opencivitas.it/it/open-data",
    note: "Confronto comunale attivo tra spesa storica e spesa standard, con valori per abitante e livello dei servizi. La differenza non viene presentata come spreco.",
    joinKeys: ["codice ISTAT Comune"],
  },
  {
    slug: "partecipazioni-pubbliche",
    name: "Censimento partecipazioni pubbliche",
    owner: "MEF · Dipartimento dell'Economia",
    area: "Società partecipate e rapporti di partecipazione",
    cadence: "Rilevazione annuale",
    coverage: "Partecipazioni dichiarate dalle amministrazioni e società partecipate",
    format: "Open data elaborabile · rilevazioni annuali",
    url: "https://www.de.mef.gov.it/it/attivita_istituzionali/partecipazioni_pubbliche/open_data_partecipazioni/index.html",
    note: "Snapshot nazionale attivo: 53.656 relazioni della rilevazione 2023, aggregati e organizzazioni dichiarate da più amministrazioni. Il drill-down completo per singola relazione richiede il successivo indice persistente.",
    joinKeys: ["codice fiscale amministrazione", "codice fiscale società"],
  },
  {
    slug: "consulenti",
    name: "Consulenti Pubblici",
    owner: "Dipartimento della Funzione Pubblica",
    area: "Consulenze e incarichi",
    cadence: "Aggiornamento per singolo incarico; controllo della piattaforma ogni 6 ore",
    coverage: "Statistiche nazionali annuali per consulenti esterni e incarichi ai dipendenti PA",
    format: "API JSON · export open data",
    url: "https://consulentipubblici.dfp.gov.it/progetto",
    note: "Snapshot nazionale attivo dal 2023: incarichi, somme erogate comunicate, incarichi conclusi e principali ripartizioni. L'anno corrente è parziale e può cambiare con nuove comunicazioni.",
  },
  {
    slug: "camera",
    name: "Camera Trasparente",
    owner: "Camera dei deputati",
    area: "Parlamento",
    cadence: "Secondo pubblicazione istituzionale",
    coverage: "Bilancio e amministrazione della Camera",
    format: "Web · documenti",
    url: "https://trasparenza.camera.it/bilancio-della-camera",
    note: "Conto consuntivo 2025 e bilancio 2026 collegati ai documenti ufficiali. Gli importi strutturati conservano la precisione verificata disponibile e il significato contabile della Camera; la UI arrotonda soltanto la presentazione.",
  },
  {
    slug: "senato",
    name: "Senato · Spese e trasparenza",
    owner: "Senato della Repubblica",
    area: "Parlamento",
    cadence: "Secondo pubblicazione istituzionale",
    coverage: "Documenti contabili censiti; importi non ancora verificati",
    format: "Web · PDF",
    url: "https://www.senato.it/relazioni-con-i-cittadini/spese-trasparenza/spese-e-trasparenza",
    note: "Il rendiconto 2024 e il bilancio 2025 sono registrati come metadati ufficiali. I PDF contabili non ereditano la licenza CC BY del portale dati.senato.it e nessun importo viene pubblicato senza acquisizione, hash e parsing verificato.",
  },
  {
    slug: "pcm",
    name: "Bilanci della Presidenza del Consiglio",
    owner: "Presidenza del Consiglio dei ministri",
    area: "Palazzo Chigi",
    cadence: "Annuale, secondo approvazione e pubblicazione istituzionale",
    coverage: "Rendiconto finanziario PCM 2024, 572 righe e 13 missioni",
    format: "XLSX · snapshot JSON verificato",
    url: "https://presidenza.governo.it/AmministrazioneTrasparente/Bilanci/BilancioPreventivoConsultivo/ContoFinanziario/2024/index.html",
    note: "Impegni, pagamenti in conto competenza e pagamenti in conto residui restano separati. Il workbook è della sola PCM e non viene sommato ai Ministeri o al Parlamento. La pagina non dichiara una licenza per il file.",
  },
];

export const sourceCounts = {
  total: publicSources.length,
};
